### ISSUE TITLE
BS mart general store not pulling data correctly

### ISSUE THREAD

**Issue by sedonastone** [xinix/core-space#101]
when using the app, the BS general store is not pulling all of the tokens available. I have ensured in the settings i only have the coreset selected and I have only checked this for the starter set tokens, but i have tried on multiple devices. Github is beyond my knowledge, but it was working last time i checked a few days ago.

**Comment by xinix** [comment]
I'll have look

**Comment by xinix** [comment]
should be fixed in version 2.0.3
