### ISSUE TITLE
General store is still pulling incorrect data.

### ISSUE THREAD

**Issue by sedonastone** [xinix/core-space#102]
Just wanted to let you know that the General store is now pulling more data and tokens, but they are still incorrect. It appears it is pulling higher value items from other places now, but it is more than should be available on things like armor and rifles etc. I am only referencing the starter set, so i cant really say if this affects any other expansions at this point, and it is still missing the health, ammo, stims etc. I just wanted to let you know!

this tool has been such a great addition to my games! thank you so much for your hard work in developing this. you are truly awesome and im so grateful for this tool! People like you make this the best experience ever, and it has been a true joy to use this tool in a modified rpg campaign as an npc store displayed on a tv during sessions. it has been so cool to be able to pull up a store shopping experience for the players when interacting with an npc vs a paper handout !

thanks again for all you have done!

**Comment by xinix** [comment]
We are getting there 🤭

I was filtering items with value 4 and higher for the general store, but it should have been 4 or lower 🫣

Version 2.0.4 should fix the issue
