### ISSUE TITLE
Question: Where do you get the asset images?

### ISSUE THREAD

**Issue by loktar00** [xinix/core-space#24]
First off this is great! Been getting into Core Space myself lately and saw this in the newsletter so had to check it out.

I'd love to help contribute, I have a few ideas / ways to possibly expand, main thing I was wondering is how you are getting the asset images. They definitely don't seem scanned. I ask because I think this could be a great app to extend by including Skill icons + descriptions along with weapon icons and their meanings (something I'm constantly flipping through the book for).

**Comment by xinix** [comment]
Hi, I got the original files from Stew himself :) I sliced the necessary icons and packed them in a single file. The skill icons are on my todo list. I'm currently finishing the post game Trade Phase, listing all the items available for sale in the different trading posts.
